repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
    - id: detect-aws-credentials
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
    - id: detect-private-key
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.7.3
  hooks:
    - id: terraform_fmt
    - id: terraform_docs